// Code generated by typeshare 1.13.4. DO NOT EDIT.
package realtime

import "encoding/json"

// Outbound `playback.command.request` payload sent to the Connect server.
//
// This is the single authoritative definition of the Connect queue command wire
// contract; the Go server's `playbackCommandPayload` is generated from it (see
// `docs/known-issues.md` Tier 1). Only the fields relevant to a given `op` are
// populated; the rest are omitted from the wire. `command_id` and `base_seq` are
// filled in by `ConnectState::send_playback_command` just before sending.
type ConnectPlaybackCommand struct {
	CommandID      *string           `json:"commandId,omitempty"`
	BaseSeq        *int64            `json:"baseSeq,omitempty"`
	Op             string            `json:"op"`
	Queue          []json.RawMessage `json:"queue,omitempty"`
	Items          []json.RawMessage `json:"items,omitempty"`
	CurrentIndex   *int64            `json:"currentIndex,omitempty"`
	AutoPlay       *bool             `json:"autoPlay,omitempty"`
	Index          *int64            `json:"index,omitempty"`
	FromIndex      *int64            `json:"fromIndex,omitempty"`
	ToIndex        *int64            `json:"toIndex,omitempty"`
	PositionMs     *int64            `json:"positionMs,omitempty"`
	TargetDeviceID *string           `json:"targetDeviceId,omitempty"`
}
type PlayingState string

const (
	PlayingStateIdle        PlayingState = "idle"
	PlayingStatePlaying     PlayingState = "playing"
	PlayingStatePaused      PlayingState = "paused"
	PlayingStateStopped     PlayingState = "stopped"
	PlayingStateInterrupted PlayingState = "interrupted"
	PlayingStateError       PlayingState = "error"
)

type ConnectPlaybackState struct {
	PlayingState      PlayingState      `json:"playingState"`
	Queue             []json.RawMessage `json:"queue"`
	CurrentIndex      *int64            `json:"currentIndex,omitempty"`
	PlayNextQueueLen  int64             `json:"playNextQueueLen"`
	CurrentPositionMs int64             `json:"currentPositionMs"`
	CurrentSongID     *string           `json:"currentSongId,omitempty"`
}
