
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async bootstrapAppState() : Promise<Result<AppBootstrap, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_app_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectServerProfile(payload: ConnectServerProfileRequest) : Promise<Result<ConnectServerProfileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_server_profile", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteServerProfile(payload: ProfileIdRequest) : Promise<Result<AppBootstrap, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_server_profile", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMusicFolders() : Promise<Result<MusicFoldersResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_music_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolderStructureRoots(payload: FolderStructureRootsRequest) : Promise<Result<FolderStructureRootsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_structure_roots", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolderStructureAlbums(payload: FolderStructureAlbumsRequest) : Promise<Result<FolderStructureAlbumsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_structure_albums", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFolderStructureAlbumSongs(payload: FolderStructureAlbumSongsRequest) : Promise<Result<FolderStructureAlbumSongsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder_structure_album_songs", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtists(payload: ArtistsRequest | null) : Promise<Result<ArtistsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artists", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistIndexes(payload: ArtistIndexesRequest | null) : Promise<Result<ArtistIndexesResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_indexes", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtist(payload: ArtistRequest) : Promise<Result<ArtistResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistInfo2(payload: ArtistInfo2Request) : Promise<Result<ArtistInfo2Response, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_info2", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMusicDirectory(payload: MusicDirectoryRequest) : Promise<Result<MusicDirectoryResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_music_directory", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAlbumSongs(payload: AlbumSongsRequest) : Promise<Result<AlbumSongsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_album_songs", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSong(payload: SongRequest) : Promise<Result<SongResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_song", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAlbumList(payload: AlbumListRequest) : Promise<Result<AlbumListResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_album_list", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCoverArt(payload: CoverArtRequest) : Promise<Result<CoverArtResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cover_art", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackGetState() : Promise<Result<PlaybackStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackSetQueue(payload: PlaybackSetQueueRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_set_queue", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPlayQueueIndex(payload: PlaybackPlayQueueIndexRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_play_queue_index", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_play") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPlayAlbum(payload: PlaybackPlayAlbumRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_play_album", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPlayFolderAlbum(payload: PlaybackPlayFolderAlbumRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_play_folder_album", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPause() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackSeek(payload: PlaybackSeekRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_seek", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackNext() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_next") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playbackPrev() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("playback_prev") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
playbackStatus: PlaybackStatus
}>({
playbackStatus: "playback-status"
})

/** user-defined constants **/



/** user-defined types **/

export type ActiveSession = { profileId: string; normalizedServerUrl: string; username: string; authKind: AuthKind; apiVersion: string; serverType: string | null; serverVersion: string | null; capabilityMatrix: CapabilityMatrix }
export type AlbumListContext = "random" | "newest" | "frequent" | "recent" | "starred" | "alphabetical_by_name" | "alphabetical_by_artist" | "by_year" | "by_genre"
export type AlbumListItem = { id: string; name: string; artist: string | null; coverArtId: string | null; year: number | null }
export type AlbumListRequest = { context: AlbumListContext; size: number | null; offset: number | null; fromYear: number | null; toYear: number | null; genre: string | null; musicFolderId: string | null }
export type AlbumListResponse = { context: AlbumListContext; albums: AlbumListItem[] }
export type AlbumSongsRequest = { id: string }
export type AlbumSongsResponse = { albumId: string; songs: SongResponse[] }
export type AppBootstrap = { profiles: SavedProfileSummary[]; activeSession: ActiveSession | null; restoreStatus: RestoreStatus; message: string | null }
export type ArtistAlbum = { id: string; parentId: string | null; title: string | null; album: string | null; name: string | null; artist: string | null; artistId: string | null; coverArtId: string | null; songCount: number | null; duration: number | null; playCount: number | null; year: number | null; genre: string | null; starred: string | null }
export type ArtistGroup = { name: string; artists: ArtistSummary[] }
export type ArtistIndexItem = { id: string; name: string }
export type ArtistIndexesRequest = { musicFolderId: string | null }
export type ArtistIndexesResponse = { artists: ArtistIndexItem[] }
export type ArtistInfo2Request = { id: string; count: number | null; includeNotPresent: boolean | null }
export type ArtistInfo2Response = { biography: string | null; musicBrainzId: string | null; lastFmUrl: string | null; smallImageUrl: string | null; mediumImageUrl: string | null; largeImageUrl: string | null; similarArtists: ArtistSummary[] }
export type ArtistRequest = { id: string }
export type ArtistResponse = { id: string; name: string; coverArtId: string | null; albumCount: number | null; artistImageUrl: string | null; starred: string | null; musicBrainzId: string | null; sortName: string | null; roles: string[]; albums: ArtistAlbum[] }
export type ArtistSummary = { id: string; name: string; coverArtId: string | null; albumCount: number | null; artistImageUrl: string | null; starred: string | null; musicBrainzId: string | null; sortName: string | null; roles: string[] }
export type ArtistsRequest = { musicFolderId: string | null }
export type ArtistsResponse = { ignoredArticles: string | null; indexes: ArtistGroup[] }
export type AuthInput = { kind: "password"; username: string; password: string } | { kind: "api_key"; apiKey: string }
export type AuthKind = "password" | "api_key"
export type CapabilityMatrix = { openSubsonic: boolean; rawExtensions: OpenSubsonicExtension[]; apiKeyAuth: boolean; indexBasedQueue: boolean; playbackReport: boolean; transcoding: boolean; transcodeOffset: boolean; songLyrics: boolean }
export type ConnectServerProfileRequest = { profileId: string | null; displayName: string | null; serverUrl: string; auth: AuthInput }
export type ConnectServerProfileResult = { status: "connected"; activeSession: ActiveSession; profiles: SavedProfileSummary[] } | { status: "auth_error"; message: string; code: number | null; helpUrl: string | null; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] } | { status: "network_error"; message: string; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] } | { status: "server_error"; message: string; code: number | null; helpUrl: string | null; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] } | { status: "unsupported_auth"; message: string; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] }
export type CoverArtRequest = { coverArtId: string; size: number | null }
export type CoverArtResponse = { localPath: string }
export type FolderStructureAlbumItem = { id: string; name: string; artist: string | null; coverArtId: string | null; year: number | null }
export type FolderStructureAlbumSongsRequest = { libraryId: string; nodeId: string; albumId: string }
export type FolderStructureAlbumSongsResponse = { libraryId: string; nodeId: string; albumId: string; songs: SongResponse[] }
export type FolderStructureAlbumsRequest = { libraryId: string; nodeId: string }
export type FolderStructureAlbumsResponse = { libraryId: string; nodeId: string; nodeName: string; albums: FolderStructureAlbumItem[] }
export type FolderStructureRootNode = { id: string; name: string }
export type FolderStructureRootsRequest = { libraryId: string }
export type FolderStructureRootsResponse = { libraryId: string; libraryName: string; source: FolderStructureSource; rootNodes: FolderStructureRootNode[] }
export type FolderStructureSource = "directory" | "indexes"
export type InterruptReason = "initial_load" | "stream_buffering_stall" | "seeking" | "full_reload"
export type LastConnectionState = "never" | "ok" | "offline" | "reauth_required"
export type MusicDirectoryChild = { id: string; parentId: string | null; path: string | null; title: string; album: string | null; albumId: string | null; artist: string | null; artistId: string | null; coverArtId: string | null; track: number | null; discNumber: number | null; year: number | null; isDirectory: boolean; mediaType: string | null }
export type MusicDirectoryRequest = { id: string }
export type MusicDirectoryResponse = { id: string; name: string; children: MusicDirectoryChild[] }
export type MusicFolderSummary = { id: string; name: string }
export type MusicFoldersResponse = { musicFolders: MusicFolderSummary[] }
export type OpenSubsonicExtension = { name: string; versions: number[] }
export type PlaybackPlayAlbumRequest = { albumId: string }
export type PlaybackPlayFolderAlbumRequest = { libraryId: string; nodeId: string; albumId: string }
export type PlaybackPlayQueueIndexRequest = { index: number }
export type PlaybackQueueEntry = { songId: string; title: string; path: string | null; artist: string | null; artistId: string | null; album: string | null; albumId: string | null; duration: number | null; coverArtId: string | null }
export type PlaybackSeekRequest = { positionMs: number }
export type PlaybackSetQueueRequest = { entries: PlaybackQueueEntry[]; currentIndex: number | null }
export type PlaybackStatus = { playingState: PlayingState; interruptReason: InterruptReason | null; pendingSeekPositionMs: number | null; queue: PlaybackQueueEntry[]; currentIndex: number | null; currentPositionMs: number; currentSongId: string | null; error: string | null }
export type PlayingState = "idle" | "playing" | "paused" | "stopped" | "interrupted" | "error"
export type ProfileIdRequest = { profileId: string }
export type RestoreStatus = "none" | "restored" | "network_error" | "connection_error" | "reauth_required"
export type SavedProfileSummary = { profileId: string; displayName: string; normalizedServerUrl: string; authKind: AuthKind; username: string; lastConnectionState: LastConnectionState; isActive: boolean }
export type SongRequest = { id: string }
export type SongResponse = { id: string; parentId: string | null; path: string | null; title: string; album: string | null; albumId: string | null; artist: string | null; artistId: string | null; coverArtId: string | null; track: number | null; discNumber: number | null; year: number | null; duration: number | null; isDirectory: boolean; mediaType: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
