// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async bootstrapAppState(): Promise<Result<AppBootstrap, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('bootstrap_app_state') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async connectServerProfile(payload: ConnectServerProfileRequest): Promise<Result<ConnectServerProfileResult, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('connect_server_profile', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async deleteServerProfile(payload: ProfileIdRequest): Promise<Result<AppBootstrap, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('delete_server_profile', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getMusicFolders(): Promise<Result<MusicFoldersResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_music_folders') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getFolderStructureRoots(payload: FolderStructureRootsRequest): Promise<Result<FolderStructureRootsResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_folder_structure_roots', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getFolderStructureAlbums(payload: FolderStructureAlbumsRequest): Promise<Result<FolderStructureAlbumsResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_folder_structure_albums', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getArtistIndexes(payload: ArtistIndexesRequest | null): Promise<Result<ArtistIndexesResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_artist_indexes', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getMusicDirectory(payload: MusicDirectoryRequest): Promise<Result<MusicDirectoryResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_music_directory', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getAlbumList(payload: AlbumListRequest): Promise<Result<AlbumListResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_album_list', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getCoverArt(payload: CoverArtRequest): Promise<Result<CoverArtResponse, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_cover_art', { payload }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type ActiveSession = {
  profileId: string;
  normalizedServerUrl: string;
  username: string;
  authKind: AuthKind;
  apiVersion: string;
  serverType: string | null;
  serverVersion: string | null;
  capabilityMatrix: CapabilityMatrix;
};
export type AlbumListContext =
  | 'random'
  | 'newest'
  | 'frequent'
  | 'recent'
  | 'starred'
  | 'alphabetical_by_name'
  | 'alphabetical_by_artist'
  | 'by_year'
  | 'by_genre';
export type AlbumListItem = { id: string; name: string; artist: string | null; coverArtId: string | null; year: number | null };
export type AlbumListRequest = {
  context: AlbumListContext;
  size: number | null;
  offset: number | null;
  fromYear: number | null;
  toYear: number | null;
  genre: string | null;
  musicFolderId: string | null;
};
export type AlbumListResponse = { context: AlbumListContext; albums: AlbumListItem[] };
export type AppBootstrap = {
  profiles: SavedProfileSummary[];
  activeSession: ActiveSession | null;
  restoreStatus: RestoreStatus;
  message: string | null;
};
export type ArtistIndexItem = { id: string; name: string };
export type ArtistIndexesRequest = { musicFolderId: string | null };
export type ArtistIndexesResponse = { artists: ArtistIndexItem[] };
export type AuthInput = { kind: 'password'; username: string; password: string } | { kind: 'api_key'; apiKey: string };
export type AuthKind = 'password' | 'api_key';
export type CapabilityMatrix = {
  openSubsonic: boolean;
  rawExtensions: OpenSubsonicExtension[];
  apiKeyAuth: boolean;
  indexBasedQueue: boolean;
  playbackReport: boolean;
  transcoding: boolean;
  transcodeOffset: boolean;
  songLyrics: boolean;
};
export type ConnectServerProfileRequest = { profileId: string | null; displayName: string | null; serverUrl: string; auth: AuthInput };
export type ConnectServerProfileResult =
  | { status: 'connected'; activeSession: ActiveSession; profiles: SavedProfileSummary[] }
  | {
      status: 'auth_error';
      message: string;
      code: number | null;
      helpUrl: string | null;
      activeSession: ActiveSession | null;
      profiles: SavedProfileSummary[];
    }
  | { status: 'network_error'; message: string; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] }
  | {
      status: 'server_error';
      message: string;
      code: number | null;
      helpUrl: string | null;
      activeSession: ActiveSession | null;
      profiles: SavedProfileSummary[];
    }
  | { status: 'unsupported_auth'; message: string; activeSession: ActiveSession | null; profiles: SavedProfileSummary[] };
export type CoverArtRequest = { coverArtId: string; size: number | null };
export type CoverArtResponse = { dataUrl: string };
export type FolderStructureAlbumItem = { id: string; name: string; artist: string | null; coverArtId: string | null; year: number | null };
export type FolderStructureAlbumsRequest = { libraryId: string; nodeId: string };
export type FolderStructureAlbumsResponse = { libraryId: string; nodeId: string; nodeName: string; albums: FolderStructureAlbumItem[] };
export type FolderStructureRootNode = { id: string; name: string };
export type FolderStructureRootsRequest = { libraryId: string };
export type FolderStructureRootsResponse = {
  libraryId: string;
  libraryName: string;
  source: FolderStructureSource;
  rootNodes: FolderStructureRootNode[];
};
export type FolderStructureSource = 'directory' | 'indexes';
export type LastConnectionState = 'never' | 'ok' | 'offline' | 'reauth_required';
export type MusicDirectoryChild = {
  id: string;
  parentId: string | null;
  path: string | null;
  title: string;
  album: string | null;
  albumId: string | null;
  artist: string | null;
  artistId: string | null;
  coverArtId: string | null;
  track: number | null;
  discNumber: number | null;
  year: number | null;
  isDirectory: boolean;
  mediaType: string | null;
};
export type MusicDirectoryRequest = { id: string };
export type MusicDirectoryResponse = { id: string; name: string; children: MusicDirectoryChild[] };
export type MusicFolderSummary = { id: string; name: string };
export type MusicFoldersResponse = { musicFolders: MusicFolderSummary[] };
export type OpenSubsonicExtension = { name: string; versions: number[] };
export type ProfileIdRequest = { profileId: string };
export type RestoreStatus = 'none' | 'restored' | 'offline' | 'reauth_required';
export type SavedProfileSummary = {
  profileId: string;
  displayName: string;
  normalizedServerUrl: string;
  authKind: AuthKind;
  username: string;
  lastConnectionState: LastConnectionState;
  isActive: boolean;
};

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit> : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    }
  );
}
